# Give exponential, sine and sigmoid functions on A

In [1]:
import numpy as np  
import csv
from sympy import *

In [2]:
matrix=open("matrix.csv")
A=np.loadtxt(matrix, dtype='int', delimiter=',')
A1=Matrix(A)
A1

Matrix([
[ 7, 2,  -3],
[-5, 6,   4],
[ 2, 3, -13]])

# Exponential Function

In [3]:
print("\n Exponential Value:")
print(np.exp(A))


 Exponential Value:
[[1.09663316e+03 7.38905610e+00 4.97870684e-02]
 [6.73794700e-03 4.03428793e+02 5.45981500e+01]
 [7.38905610e+00 2.00855369e+01 2.26032941e-06]]


### Proper Matrix Format Output

In [4]:
EXP1=Matrix(np.exp(A))
EXP1

Matrix([
[   1096.63315842846, 7.38905609893065,  0.0497870683678639],
[0.00673794699908547, 403.428793492735,    54.5981500331442],
[   7.38905609893065, 20.0855369231877, 2.26032940698105e-6]])

# Sine Function

In [5]:
print("\n Sine Value:")
print(np.sin(A * np.pi / 180))


 Sine Value:
[[ 0.12186934  0.0348995  -0.05233596]
 [-0.08715574  0.10452846  0.06975647]
 [ 0.0348995   0.05233596 -0.22495105]]


### Proper Matrix Format Output

In [6]:
SINE=Matrix(np.sin(A * np.pi / 180))
SINE

Matrix([
[  0.121869343405147,  0.034899496702501, -0.0523359562429438],
[-0.0871557427476582,  0.104528463267653,  0.0697564737441253],
[  0.034899496702501, 0.0523359562429438,  -0.224951054343865]])

# Sigmoid Function

In [7]:
print("\n Sigmoid Value:")
def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))

print(sigmoid(A))


 Sigmoid Value:
[[9.99088949e-01 8.80797078e-01 4.74258732e-02]
 [6.69285092e-03 9.97527377e-01 9.82013790e-01]
 [8.80797078e-01 9.52574127e-01 2.26032430e-06]]


### Proper Matrix Format Output

In [8]:
SIG=Matrix(sigmoid(A))
SIG

Matrix([
[  0.999088948805599, 0.880797077977882,  0.0474258731775668],
[0.00669285092428486, 0.997527376843365,   0.982013790037908],
[  0.880797077977882, 0.952574126822433, 2.26032429790357e-6]])